apiVersion: v1
kind: Service
metadata:
  name: generator-service
  labels:
    name: generator-service
    app: as
spec:
  selector:
    type: generator-pod
    app: as
  ports:
    - port: 8080
      targetPort: 8080
