apiVersion: v1
kind: Service
metadata:
  name: generator-service-exposed
  labels:
    name: generator-service-exposed
    app: as
spec:
  selector:
    type: generator-pod
    app: as
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  type: NodePort
