apiVersion: v1
kind: Service
metadata:
  name: ui-service-exposed
  labels:
    name: ui-service-exposed
    app: as
spec:
  selector:
    type: ui-pod
    app: as
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31002
  type: NodePort
